

all: clean multicast multicast_listener

multicast:
	gcc multicast.c -g -o multicast

multicast_listener:
	gcc multicast_listener.c -g -o multicast_listener

clean: 
	rm multicast
	rm multicast_listener